service: serverless-lambda-exercise

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  s3TriggerToLambda:
    handler: index.handler
    name: s3-trigger-to-lambda

  countItemsInS3Bucket:
    handler: index.handler
    name: count-items-in-s3-bucket