service: serverless-lambda-exercise

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  s3TriggerToLambda:
    handler: src/s3TriggerToLambda/index.s3TriggerToLambda
    name: s3-trigger-to-lambda

  countItemsInS3Bucket:
    handler: src/countItemsInS3Bucket/index.countItemsInS3Bucket
    name: count-items-in-s3-bucket