service: serverless-lambda-exercise

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  s3TriggerToLambda:
    handler: src/s3/s3TriggerToLambda.s3TriggerToLambda
    name: s3-trigger-to-lambda

  countItemsInS3Bucket:
    handler: src/s3/countItemsInS3Bucket.countItemsInS3Bucket
    name: count-items-in-s3-bucket